
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://database-1.cbcnox9o9es0.ap-southeast-1.rds.amazonaws.com:3306/efms_db
      username: admin
      password: Shengli1021

  #日期时间格式化配置信息
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"

#上传文件配置信息
file:
  uploadPath: D:\\Projrct-EFMS\\upload\\
  #  uploadPath: imgupload/
  accessPath: /image/

